[package]
name = "arkin-data-provider-binance"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arkin-core = { path = "../arkin-core" }

tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-rustls = { workspace = true }
anyhow = { workspace = true }
kanal = { workspace = true }
time = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
backoff = { workspace = true }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
thiserror = { workspace = true }
typed-builder = { workspace = true }
tokio-tungstenite = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }
